application: travelstoryme
version: v1
runtime: python27
api_version: 1
threadsafe: yes


builtins:
- appstats: on


handlers:

- url: /static
  static_dir: static

- url: /web/bower_components
  static_dir: bower_components

- url: /web/node_modules
  static_dir: node_modules


- url: /web/.*
  script: main.app
  secure: always


- url: /api/.*
  script: main.app
  secure: always


- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin


- url: /.*
  script: main.app




libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest
- name: pycrypto
  version: "2.6"